version: '2'
services:
  db:
    image: postgres:latest
    container_name: db
    volumes:
      - /var/lib/postgresql
  redis:
    image: redis:latest
    container_name: redis
  spacedock:
    build: .
    container_name: spacedock
    volumes:
      - .:/opt/spacedock
    ports:
      - "8000:8000"
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
